{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rag-model-weights
  annotations:
    "helm.sh/resource-policy": keep

spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.volumes.modelWeights.size }}
  storageClassName: {{ .Values.persistence.storageClass }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rag-data
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.volumes.data.size }}
  storageClassName: {{ .Values.persistence.storageClass }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rag-logs
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.volumes.logs.size }}
  storageClassName: {{ .Values.persistence.storageClass }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rag-venv
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.volumes.venv.size }}
  storageClassName: {{ .Values.persistence.storageClass }}
{{- end }}
